module.exports = {
  uri: 'https://randallreilly.native-x.parameter1.com',
  placements: {
    'ccj-breaking-news': {
      sponsor: 'TBD',
    },
    'ccj-daily': {
      sponsor: '5fd273a413052500013687a7',
      'rotation-a': '5fd273a9b192ef0001843fe2',
      'rotation-b': '5fd273ae13052500013687c3',
      'rotation-c': '5fd273b4b192ef0001843ff5',
      'rotation-d': '5fd273bab192ef0001843fff',
      'rotation-e': '5fd273c013052500013687df',
    },
    'ccj-equipment-weekly': {
      sponsor: 'TBD',
      'rotation-a': 'TBD',
      'rotation-b': 'TBD',
      'rotation-c': 'TBD',
      'rotation-d': 'TBD',
      'rotation-e': 'TBD',
    },
    'ccj-technology-weekly': {
      sponsor: 'TBD',
      'rotation-a': 'TBD',
      'rotation-b': 'TBD',
      'rotation-c': 'TBD',
      'rotation-d': 'TBD',
      'rotation-e': 'TBD',
    },
    'eqw-better-roads': {
      sponsor: 'TBD',
      'rotation-a': 'TBD',
      'rotation-b': 'TBD',
      'rotation-c': 'TBD',
      'rotation-d': 'TBD',
      'rotation-e': 'TBD',
    },
    'eqw-big-iron-dealer': {
      sponsor: 'TBD',
      'rotation-a': 'TBD',
      'rotation-b': 'TBD',
      'rotation-c': 'TBD',
      'rotation-d': 'TBD',
      'rotation-e': 'TBD',
    },
    'eqw-daily': {
      sponsor: 'TBD',
      'rotation-a': 'TBD',
      'rotation-b': 'TBD',
      'rotation-c': 'TBD',
      'rotation-d': 'TBD',
      'rotation-e': 'TBD',
    },
    'hwt-weekly': {
      sponsor: 'TBD',
      'rotation-a': 'TBD',
      'rotation-b': 'TBD',
      'rotation-c': 'TBD',
      'rotation-d': 'TBD',
      'rotation-e': 'TBD',
    },
    'ovd-breaking-news': {
      sponsor: 'TBD',
    },
    'ovd-custom-rigs': {
      sponsor: 'TBD',
      'rotation-a': 'TBD',
      'rotation-b': 'TBD',
      'rotation-c': 'TBD',
      'rotation-d': 'TBD',
      'rotation-e': 'TBD',
    },
    'ovd-daily': {
      sponsor: '5fd192ccc19f3b0001d71741',
      'rotation-a': '5fd192d7b192ef00018433d0',
      'rotation-b': '5fd192dac19f3b0001d7175d',
      'rotation-c': '5fd192dfc19f3b0001d71767',
      'rotation-d': '5fd192e2b192ef00018433e3',
      'rotation-e': '5fd192e6c19f3b0001d7177a',
    },
    'tlc-daily': {
      sponsor: 'TBD',
      'rotation-a': 'TBD',
      'rotation-b': 'TBD',
      'rotation-c': 'TBD',
      'rotation-d': 'TBD',
      'rotation-e': 'TBD',
    },
    'tn-daily': {
      sponsor: 'TBD',
      'rotation-a': 'TBD',
      'rotation-b': 'TBD',
      'rotation-c': 'TBD',
      'rotation-d': 'TBD',
      'rotation-e': 'TBD',
    },
    'tn-she-drives': {
      sponsor: 'TBD',
      'rotation-a': 'TBD',
      'rotation-b': 'TBD',
      'rotation-c': 'TBD',
      'rotation-d': 'TBD',
      'rotation-e': 'TBD',
    },
    'tps-daily': {
      sponsor: 'TBD',
      'rotation-a': 'TBD',
      'rotation-b': 'TBD',
      'rotation-c': 'TBD',
      'rotation-d': 'TBD',
      'rotation-e': 'TBD',
    },
    'tps-successful-dealer': {
      sponsor: 'TBD',
      'rotation-a': 'TBD',
      'rotation-b': 'TBD',
      'rotation-c': 'TBD',
      'rotation-d': 'TBD',
      'rotation-e': 'TBD',
    },
    'tps-weekly': {
      sponsor: 'TBD',
      'rotation-a': 'TBD',
      'rotation-b': 'TBD',
      'rotation-c': 'TBD',
      'rotation-d': 'TBD',
      'rotation-e': 'TBD',
    },
  },
};
